[workspace]

members = [
  "crates/*"
]

[workspace.dependencies]
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v4"] }
